### ISSUE TITLE
Space Tour: Full screen option

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-modular#139] opened 2017-08-08 09:56 UTC
Space Tour needs a button to go full screen. Like in original Pannellum.

![spacetour2](https://user-images.githubusercontent.com/4581081/29066791-f22b0dae-7c4d-11e7-8aac-06cb551a5694.png)

![spacetour](https://user-images.githubusercontent.com/4581081/29066779-e6ef068e-7c4d-11e7-94c1-d6357e6fb741.png)

**Comment by Madhuvanthi-A** [comment] 2017-08-08 11:06
Duplicate of issue #74

**Closed as completed by Madhuvanthi-A** 2017-08-08 11:06 UTC
