### ISSUE TITLE
#38 Videos are not playing in Chromium browser

### ISSUE THREAD

**Issue by pradeepc** [janastu/ncbs-modular#38] opened 2017-07-23 08:48 UTC

**Comment by salus-sage** [comment] 2017-07-23 22:42
@shalinia can you please assist @Madhuvanthi-A with cross browser testing, mostly to find the issue and also a possible solutions

**Comment by Madhuvanthi-A** [comment] 2017-07-24 03:48
Video is playing in Chromium browser.

**Comment by salus-sage** [comment] 2017-07-27 23:08
Can we please have proper report updating on cross browser testing?

**Comment by salus-sage** [comment] 2017-07-27 23:12
The cross browser testing report to be updated in issue #45

**Comment by pradeepc** [comment] 2017-07-31 15:39
The NCBS Server IP: 158.144.176.250 is too slow.
![ncbs-server-ping-status](https://user-images.githubusercontent.com/1224443/28785599-8041eb6e-7634-11e7-80b4-374dff4bec2c.png)

**Comment by tripToner** [comment] 2017-09-13 11:18
Duplicate of issue #175

**Closed as completed by tripToner** 2017-09-13 11:18 UTC
Labels: help wanted, question
