### ISSUE TITLE
From site map if user clicks on any chapter, the chapter header and also sometimes  half the content is hidden, the user need to scroll up

### ISSUE THREAD

**Issue by pratiksha6656** [janastu/ncbs-modular#266] opened 2017-12-27 11:41 UTC

**Comment by salus-sage** [comment] 2017-12-28 13:23
In my updated chrome and firefox, i couldn't recreate this bug.

**Comment by salus-sage** [comment] 2017-12-29 12:20
duplicate of issue #259 the bug is valid for all links in footer,

**Closed as completed by salus-sage** 2017-12-29 12:20 UTC
Labels: bug
